version: '3'

services:
    app:
        container_name: service-api
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www/api
        ports:
            - "8081:80"
        environment:
            - "AUTH_TOKEN_API=truongbo"
        volumes:
            - ./storage/logs/nginx:/var/log/nginx
            - ./.docker/.composer:/root/.composer
