version: '3'

services:
    app:
        container_name: service-api
        build:
            context: ./
            dockerfile: Dockerfile
        working_dir: /var/www/api
        restart: unless-stopped
        depends_on:
            - signature
        ports:
            - "${PORT_APP}:80"
        volumes:
            - ./app/storage/logs/nginx:/var/log/nginx
            - ./.docker/.composer:/root/.composer
    signature:
        container_name: signature
        image: ghcr.io/pablouser1/signtok:master
        restart: unless-stopped
        ports:
            - "${PORT_SIGNATURE}:8080"

