<?php

return [
    'request_headers_tiktok' => [
        "x-secsdk-csrf-version: 1.2.5",
        "x-secsdk-csrf-request: 1"
    ],
    'signature_service' => env('ENDPOINT_TIKTOK_SIGNATURE'),
    'cookie_domain' => '.tiktok.com',
    'tiktok_cookie' => array(
        0 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1673352370.583624,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'ak_bmsc',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => 'F6333CF53CD843AD450BA0858C5AB1AA~000000000000000000000000000000~YAAQNQqrcSzayvCEAQAALgwlmxKr2pQNumSv5zxcw2pcWAVOJQNfNJIPkso2hK2MQOGh0szt/BHlOTWPWhG+MhMGSgAUPNgKo9RM2g9iDrBtSk4ileZMAjFlQAGjJtD7hjC/tn8mtD+8ocZFqEzGjiWEpFKNaGvjxznJLTrtFpd5Bs5PyPzrZzuRwxxNv0EJtMIJ3PGEMCqfi/GjPbvo+FVHyagPpPhPWkCyj7Kor8UjliUOXVStn3qc9/DXGNF7Rqw/U7L8O1xfBgzJYBt5VYdMbAOvOcew2j3cvzfgwCs65cgDslqETHumFbWsqPvOFPSo94e4GAz7mw+MMx9MIqaj2yYMFi1uysTqU1XxD82qzkAnbZQJlpcA0luWNnDV3+wdXXF0UJytvWUb3HF3wO7wbozX7+GzjHrMEAvK8aeo2GuVI/d4NcQnzi26KaCtixPhhFN8u7w9OtShsy+4hveeTGdkgUpd6RugTw8PTrPgCF727eA6Rj4LoA==',
            ),
        1 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1701143835.329073,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'tt-target-idc-sign',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => 'qGOppM3Q_ubgkZgteggH1ubnYPDaMeum0KgizGXct9e108bIXQa8M_AGhJTR4Drw5erK2YinBGjbuMEU5BrjCYf2PVX_dZCdhbVA6omVyf5_eIjesE37U2rMIOEej0bslOhC_H88kiUa5LFsJn9M6kVj8mnFVV_LgS09b945IOxI39oHqQ5AbwC4fc1vaIuTziw-Z89gQovvf_2Dpv4r1QzCAzw_trFSF3rgggfhvVzruqi7HN-SFxxuEMHB35bTsHzgAxBUeZT-qGWJmxvIr1bQ6ih4EeNEtcSgFsW5-dKUnJaMJ0SbxjxQY9zChkty20AhfqffKil-Uy4gPAUdUr9r0JRbh-r_WXXooM0wvwKp5V1b4Lw2YaVr-4Fs2AKYybsuovKHHHVqqqhyNA-SeQ28dfvMk8Swuh3uhl97ySKnvf1-llMJBaeoZ3_p7tuyqbXzIpNcvt4jEa4ZcW97VtADwqDtjb3XCh1iX36JKQd7Mzu3LEQ_89Lv7f1dCAQ3',
            ),
        2 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1704881173.257108,
                'hostOnly' => false,
                'httpOnly' => false,
                'name' => '_abck',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => 'FF2F620B4E571A80776F85EB86DA8F0D~0~YAAQNQqrcSXayvCEAQAA9wYlmwlvE3RPrU2B/l/Jsosyn+cnCjjb2bG6jxF8320FdPZZ0BBdgd5LYKQAy9IzMX3dwFPyrH9alp0yjxGonESV9VHNwPRQbWVxBN0NeLphNnl7X9nr/2LVkCz3/8Z1n5sF946nxGNXIwS1dtRvkvUjKJxUt1GccwUnfxF/5zcjKXzqOjrbZcqO0G1nngFPOh6Rei1/XA3uivm9PkDmaxj2xkB9pZLC0rhLRbSFy0XvCz89YRniPm4R7dzuOPGOqM4Hq5xYx3oVVel4XsaoijFBEySBLFahUY+OMmp08idZcoR/KW86TJbbW/4lrp1RVVFFm81gVrttpO96yutT+UZxSIv293xoc0XbMuSUWkb5gm3M65JIktsZn0WaH8FECFMrmS8XiHk=~-1~-1~-1',
            ),
        3 =>
            array(
                'domain' => 'www.tiktok.com',
                'hostOnly' => true,
                'httpOnly' => false,
                'name' => 'csrf_session_id',
                'path' => '/',
                'sameSite' => 'no_restriction',
                'secure' => true,
                'session' => true,
                'storeId' => NULL,
                'value' => '462309c28da30fed8216c1c83653d532',
            ),
        4 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1674209183.568935,
                'hostOnly' => false,
                'httpOnly' => false,
                'name' => 'msToken',
                'path' => '/',
                'sameSite' => 'no_restriction',
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => '4tRj91XslZazs-o-q9RNoZ7IHzy3JARfQY6XjsJ_biYblRpmxAnfPBItmwU_2ayj1_SkFeBOD83kv2aEEiZ3PgZ9Rsux6Y8YNkEmTEJbzHNgjOim7Whn7XtBPQhLMvnO5oYc_RBWmqUPL29v',
            ),
        5 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1704336057.383166,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'sid_guard',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => '1770d651535d6b8659fe6f0e07efeda3%7C1673232057%7C5184000%7CFri%2C+10-Mar-2023+02%3A40%3A57+GMT',
            ),
        6 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1704881180.063637,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'ttwid',
                'path' => '/',
                'sameSite' => 'no_restriction',
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => '1%7CDiLxUdk6rotE5xXYQWFQo2zLi--PwAv433gZX11PMUc%7C1673345180%7C3b9786fb5a6bfe5d3e406c5b902cb22d40f0b6bb3aad010f41321935e7b302a0',
            ),
        7 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.096501,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'store-country-code-src',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => 'uid',
            ),
        8 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.383214,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'uid_tt',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => 'acf0b272782e270641facfbea76ad481f85417291b605166715f2956eca43b9e',
            ),
        9 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1674791815.973265,
                'hostOnly' => false,
                'httpOnly' => false,
                'name' => 'passport_csrf_token_default',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => '49e067d352725a44fb7ca95163b711c5',
            ),
        10 =>
            array(
                'domain' => 'www.tiktok.com',
                'expirationDate' => 1681121183,
                'hostOnly' => true,
                'httpOnly' => false,
                'name' => 'msToken',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => '4tRj91XslZazs-o-q9RNoZ7IHzy3JARfQY6XjsJ_biYblRpmxAnfPBItmwU_2ayj1_SkFeBOD83kv2aEEiZ3PgZ9Rsux6Y8YNkEmTEJbzHNgjOim7Whn7XtBPQhLMvnO5oYc_RBWmqUPL29v',
            ),
        11 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.096408,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'store-idc',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => 'useast2a',
            ),
        12 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.383323,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'ssid_ucp_v1',
                'path' => '/',
                'sameSite' => 'no_restriction',
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => '1.0.0-KDJhZTc0ODA0NzEyZTJmYjk4YTkwNjI3YTc3ODgxYmRkZmI0YjEyMTgKIAiCiJHg5s7s5mEQuf3tnQYYswsgDDDM67iOBjgHQPQHEAEaA3NnMSIgMTc3MGQ2NTE1MzVkNmI4NjU5ZmU2ZjBlMDdlZmVkYTM',
            ),
        13 =>
            array(
                'domain' => '.www.tiktok.com',
                'expirationDate' => 1699265179,
                'hostOnly' => false,
                'httpOnly' => false,
                'name' => 'tiktok_webapp_theme',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => 'dark',
            ),
        14 =>
            array(
                'domain' => '.www.tiktok.com',
                'expirationDate' => 1673949979,
                'hostOnly' => false,
                'httpOnly' => false,
                'name' => '__tea_cache_tokens_1988',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => '{%22_type_%22:%22default%22%2C%22user_unique_id%22:%227159070234392020481%22%2C%22timestamp%22:1666850944770}',
            ),
        15 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1707039150.449837,
                'hostOnly' => false,
                'httpOnly' => false,
                'name' => '_ttp',
                'path' => '/',
                'sameSite' => 'no_restriction',
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => '2Gtc4wTHRGnc4l7FJd2kAeqfkTt',
            ),
        16 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1673359570.257358,
                'hostOnly' => false,
                'httpOnly' => false,
                'name' => 'bm_sz',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => '5C9882AAE9B8B14B9F82DD650BB2B128~YAAQNQqrcSjayvCEAQAA9wYlmxIJpTHhIb+SvXzttGY6AMTosXErgS+fV9cQN9DYpY9h9y6xllz4KWA6Hl62E1AdJEV7qNGxRBhTbhEiCwbDmpwWVKl8eYdHudk9iBeJoD9nHV+/35IncL9d9cmcRdqVXEVBmVBRacVKjRC9X5qjrZCVfqm+o8lBP+2oK8lPk2H2Q9O7i/J2NoiutU9EgwQb1E3f3JGEjHxeSo2cmvCup6t2EbCBKW+OOo/avOTZvb2eejt41EQWmCbHkb4boFM3MG4vJpYcnojj3nqMzk37dfE=~4536368~4339011',
            ),
        17 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1674791834.81773,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'cmpl_token',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => 'AgQQAPOFF-RO0rHzXNHkNp07-Tu5QQydf4MOYMsCmQ',
            ),
        18 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1704881181.536694,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'odin_tt',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => '9a3e91afee6e667950ec8d3ea716ef6da11b9a4cb69bdecef11501e3df8ada32b106aeea1cf65b289242524cd71c4ea05a0c3b95d2e32ba71a0d700f8b8af92a1e197a268eaeb74a4d9852aa05e0b6b6',
            ),
        19 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1674791815.973223,
                'hostOnly' => false,
                'httpOnly' => false,
                'name' => 'passport_csrf_token',
                'path' => '/',
                'sameSite' => 'no_restriction',
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => '49e067d352725a44fb7ca95163b711c5',
            ),
        20 =>
            array(
                'domain' => '.www.tiktok.com',
                'hostOnly' => false,
                'httpOnly' => false,
                'name' => 'passport_fe_beating_status',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => true,
                'storeId' => NULL,
                'value' => 'true',
            ),
        21 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.383271,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'sessionid',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => '1770d651535d6b8659fe6f0e07efeda3',
            ),
        22 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.383287,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'sessionid_ss',
                'path' => '/',
                'sameSite' => 'no_restriction',
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => '1770d651535d6b8659fe6f0e07efeda3',
            ),
        23 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.383255,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'sid_tt',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => '1770d651535d6b8659fe6f0e07efeda3',
            ),
        24 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.383304,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'sid_ucp_v1',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => '1.0.0-KDJhZTc0ODA0NzEyZTJmYjk4YTkwNjI3YTc3ODgxYmRkZmI0YjEyMTgKIAiCiJHg5s7s5mEQuf3tnQYYswsgDDDM67iOBjgHQPQHEAEaA3NnMSIgMTc3MGQ2NTE1MzVkNmI4NjU5ZmU2ZjBlMDdlZmVkYTM',
            ),
        25 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.096477,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'store-country-code',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => 'vn',
            ),
        26 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.096519,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'tt-target-idc',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => false,
                'session' => false,
                'storeId' => NULL,
                'value' => 'alisg',
            ),
        27 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1673366773.256894,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'tt_chain_token',
                'path' => '/',
                'sameSite' => NULL,
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => 'QSwxZpobHHEHqqJA/7HaUA==',
            ),
        28 =>
            array(
                'domain' => '.tiktok.com',
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'tt_csrf_token',
                'path' => '/',
                'sameSite' => 'lax',
                'secure' => true,
                'session' => true,
                'storeId' => NULL,
                'value' => 'O359PU6S-VSjhkSADTxlyZJdEKGZgMzhnL10',
            ),
        29 =>
            array(
                'domain' => '.tiktok.com',
                'expirationDate' => 1678416057.383235,
                'hostOnly' => false,
                'httpOnly' => true,
                'name' => 'uid_tt_ss',
                'path' => '/',
                'sameSite' => 'no_restriction',
                'secure' => true,
                'session' => false,
                'storeId' => NULL,
                'value' => 'acf0b272782e270641facfbea76ad481f85417291b605166715f2956eca43b9e',
            ),
    ),
];
