<?php

return [
    'request_headers_tiktok' => [
        "x-secsdk-csrf-version: 1.2.5",
        "x-secsdk-csrf-request: 1"
    ],
    'signature_service'      => env('ENDPOINT_TIKTOK_SIGNATURE', 'http://localhost:8080/signature'),
    'cookie_domain'          => '.tiktok.com',
    'tiktok_cookie'          => [
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671945123.2013,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "ak_bmsc",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "762A9F30DD5A91453B1289720604A74E~000000000000000000000000000000~YAAQExBFdh9cvPCEAQAAdShERxL4HRrDaj2QJS1TG4BZNJZEsswr5Df16sbGGM3Xagkri9/D54Czj6FyUfe3wMAVVA9Yu7fCUeWun7yMfomEINoyGAW+Ta73vO4f8QlV1ZLuhL1ib7BybjpTFU1vSm2Rl2+hQEjRARjZ27cR48cVafZP8CxgM+adUjBmWHr/0q8XFLckLXhXv5sCuhW/1jutfKocP6odGmV5vYX7K7T5Yaj+bZf3LZexbYnMOEKVZRp8hK9xVd+VfTdVlPKcwYPDQTRkx1HlDuuIwLcSKv3XNdLXjV5umM42WSeFTo6Ym5zXqnHBVXxmabLy+hcP9GeQG3dEAD0l5/Xe/0m52aWIbZsawyxGUC0zSRJX70rWmz+ZYD02j0MMjYCiL0zZkpDkyGNnRL3Ykf/UWh76Zv+MKmvR/FAYlgr19FtwFUE+W/AI8kbcy4wc6XfyjA0MDqdgJdO+1kgumQ0CgXNSFX1yIuYqDYpKqM0="
        ],
        [
            "domain"         => ".www.tiktok.com",
            "expirationDate" => 1679236476,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "_tea_utm_cache_3053",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "{%22utm_source%22:%22telegram%22%2C%22utm_medium%22:%22android%22%2C%22utm_campaign%22:%22client_share%22}"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1700373247.1984,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "tt-target-idc-sign",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "PIwGp8U0xtl_FBX3fKpTyHysmXS_-7DyJhoCL7hOPbkh_GbnRj0lFpkHL0nKykRyV5afgf5121llJgIkKk3wchxaPwNU0Avo_0AJgtYcbRPby-JmKxSvWWbYV700kfmX5oJDGFEFXawnxvV91KRTOJHJNygcOrx6pcsD8vJCjo8a-tPyCJZPM4tWwJpUP7431IgIe8HQuXgV3oRyUuM0iktEtEfdEIoI30uTUnNidy6J4UTPmAKziFCzIQxfrByKWHZNitEV_1yU4IwApoCQWJaGs3cMRlZzDfGp5NHqCc9yCcwZ-5d7neJ5UkyXH-aZjNz8Azemu7vAyHK-XRHYD4qAn9qq4nt6rEPHwvvl00gQX26JtUsh2QwjBU44QiXImqeP0i8yWNJztMf1lK-J0BUSFVcT3WP7pqYabbF71mUcvYaSqfa7EGLp-9mdKB8g04qmQh8e3EQn4MIdkBce--nH4gvCesk2LRDWhzvc-7VC7ZEo7PxjCMKRUk7bFPNp"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1703473925.3869,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "_abck",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "0171036D1D3B1BDE02B0BF136B02617F~0~YAAQExBFdg5cvPCEAQAAWCFERwnJKtd95qCcCUBhN0HHTwiN7Vkzx9fqQyxRsD6fILf+Yx/l4cOhKUJIL9b5QoCS3RDnPPy7PTuRmvfg3t4LcF0c4YWjlg6sPRjsNnqpjiZ63j9Uz+26+CVXepwmF1pPQ73HKEAJm0q12SqlENGKg/lKvdG75uaO8WBj1geJNOMUkcnb91PLoakmrBrwO9ul2jbzHLWVNtVLdtwJjjGqm7HqRmHDoW8ui1oPSiBJbItTPSATnFGaC2dOHKayvWSEmuneA4AjflNTZbBeLkLt/HS0HwB6Vmg6bLZeN/SE0e+k9ReHNS7/tVtc4zH1jZA8Njbp64KfwGxT4oqxOgl3IDbG41WFN6f0Am+/fNdmiDNyf70dPnR1IcCEnO2L0K0mNhT+yfv0~-1~-1~-1"
        ],
        [
            "domain"   => "www.tiktok.com",
            "hostOnly" => true,
            "httpOnly" => false,
            "name"     => "csrf_session_id",
            "path"     => "/",
            "sameSite" => "no_restriction",
            "secure"   => true,
            "session"  => true,
            "storeId"  => null,
            "value"    => "fe0e0bf5e7d23592b9e6201679a86d7f"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1672801988.6859,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "msToken",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "SOBc91Ob2nNn7rbonxmIk1-ZObndA54ANVWCCvbtQuIuo7STnigpcsy_cCH7zoSEyUVixI5ar9bvgpasNJSjqgX176fHDf67Ag04qDEKssNQsV3vQBcYRGLbkZJLFL5bIrlAQTqIS8ws_TqP"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1702031813.3183,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sid_guard",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "21c0b1411ef51235a2c4f7a2529112b8%7C1670927813%7C5184000%7CSat%2C+11-Feb-2023+10%3A36%3A53+GMT"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1703473927.8615,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "ttwid",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "1%7CpSUChnnK5qxbEGOtAeP_vGf2TksGyUkg32-sun6niZ8%7C1671937927%7C828bffb5c670ba9994d43884f5389ed46a503425cad4f09104a0c7ad93149306"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.6399,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "store-country-code-src",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "uid"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.3184,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "uid_tt",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "73ae82143fef14c0339143e94f7b348ccae6a275ba50558427eb39a07e2ea985"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1673781549.433,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "passport_csrf_token_default",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "e47171f7a9c7c97cc23ac605d13bfb5d"
        ],
        [
            "domain"         => "www.tiktok.com",
            "expirationDate" => 1679713988,
            "hostOnly"       => true,
            "httpOnly"       => false,
            "name"           => "msToken",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "SOBc91Ob2nNn7rbonxmIk1-ZObndA54ANVWCCvbtQuIuo7STnigpcsy_cCH7zoSEyUVixI5ar9bvgpasNJSjqgX176fHDf67Ag04qDEKssNQsV3vQBcYRGLbkZJLFL5bIrlAQTqIS8ws_TqP"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.6398,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "store-idc",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "useast2a"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.3186,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "ssid_ucp_v1",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "1.0.0-KDk5ODk2NTFkNjgyYjU3NmE5MjY0YjhhMTk4YWFmMzI5ODZhMGQ5NzcKIAiCiJHg5s7s5mEQxavhnAYYswsgDDDM67iOBjgHQPQHEAEaA3NnMSIgMjFjMGIxNDExZWY1MTIzNWEyYzRmN2EyNTI5MTEyYjg"
        ],
        [
            "domain"         => ".www.tiktok.com",
            "expirationDate" => 1697857926,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "tiktok_webapp_theme",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "dark"
        ],
        [
            "domain"         => ".www.tiktok.com",
            "expirationDate" => 1672542726,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "__tea_cache_tokens_1988",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "{%22_type_%22:%22default%22%2C%22user_unique_id%22:%227164296904736736769%22%2C%22timestamp%22:1668596940430}"
        ],
        [
            "domain"         => ".www.tiktok.com",
            "expirationDate" => 1672065276,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "_tea_utm_cache_1988",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "{%22utm_source%22:%22telegram%22%2C%22utm_medium%22:%22android%22%2C%22utm_campaign%22:%22client_share%22}"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1704963160.4775,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "_ttp",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "2HLlrYYxhO8eGZlzE5re9j6js5E"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671945138.0108,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "bm_sv",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "B636362059B92C25462BBFE95B615031~YAAQExBFdk5dvPCEAQAAZttERxKOd894CsfCjMrX3lSiFB5R3jJJ1z9NrrOfJOTNsXr77nVlOX0RAGBkvC6ImtDNf+IuVifoBhOgfM8rios58hM8MnBEtxbuV2pF0dYNXYHgAB/Ha+rzpTQToYvpGRc8d9PPD7NtPCYSBAD4na/MbAHwuvA0uRzkaAnEgwTT5TQPCa87JoGee5AD0ltGyfPQeWQQzmWSnHvseQgw3k5vUBE4IRgYHLB49YcZFmrm~1"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671952323.387,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "bm_sz",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "3250E9A38312267CF5A47A2C1892AE25~YAAQExBFdhFcvPCEAQAAWCFERxLSMjvTo4B9mAVYGdmdRbYm/WVZLZ3yYy8XFUhgKglf1Q7mE1KrzgAOCHFA9ZWFMuQa/stl93lbPw3JJL4gU08R73cAmadcGyofAeWeshs1TKzCxMd0fjElkp6MqC4ndjZXvBuUJ1vvkEq9emn95tT+2Dob4wvTxj1ZlBO7uu5vnXrkd5hw3GmWjCc8yQjQ4DM2uPdTMDB/zhKDOVZSQB8Mvg7cjf8v1bP5RNki/ZeXwI9ZO2XQIUjsxmAoo5FxAz4iiUs/ZrM2VxGjSqZaPoE=~3290167~3490096"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1674021246.8015,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "cmpl_token",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "AgQQAPOFF-RO0rHzXNHkNp07-Q0rIAfcv4MOYMvwtg"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1703473927.8374,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "odin_tt",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "b36446a1e7a5db0df12663df6835d7fc16a174180612e8bfd07d97bba4c6184b18600582bb37a70a173e66ccaa83676c68c69d580270a3ceb6b486f12781cab34eab7a52ddc30caaae5975f33bef48c8"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1673781549.4329,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "passport_csrf_token",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "e47171f7a9c7c97cc23ac605d13bfb5d"
        ],
        [
            "domain"   => ".www.tiktok.com",
            "hostOnly" => false,
            "httpOnly" => false,
            "name"     => "passport_fe_beating_status",
            "path"     => "/",
            "sameSite" => null,
            "secure"   => false,
            "session"  => true,
            "storeId"  => null,
            "value"    => "true"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.3185,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sessionid",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "21c0b1411ef51235a2c4f7a2529112b8"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.3185,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sessionid_ss",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "21c0b1411ef51235a2c4f7a2529112b8"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.3185,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sid_tt",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "21c0b1411ef51235a2c4f7a2529112b8"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.3186,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sid_ucp_v1",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "1.0.0-KDk5ODk2NTFkNjgyYjU3NmE5MjY0YjhhMTk4YWFmMzI5ODZhMGQ5NzcKIAiCiJHg5s7s5mEQxavhnAYYswsgDDDM67iOBjgHQPQHEAEaA3NnMSIgMjFjMGIxNDExZWY1MTIzNWEyYzRmN2EyNTI5MTEyYjg"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.6399,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "store-country-code",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "vn"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.6399,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "tt-target-idc",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "alisg"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671959525.3867,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "tt_chain_token",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "jyiw3wM5LIOMS1AVprH+dQ=="
        ],
        [
            "domain"   => ".tiktok.com",
            "hostOnly" => false,
            "httpOnly" => true,
            "name"     => "tt_csrf_token",
            "path"     => "/",
            "sameSite" => "lax",
            "secure"   => true,
            "session"  => true,
            "storeId"  => null,
            "value"    => "qWlDzUlt-NbIHSgHaBD-xhOyES97OElV9Ek8"
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1676111813.3185,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "uid_tt_ss",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "73ae82143fef14c0339143e94f7b348ccae6a275ba50558427eb39a07e2ea985"
        ]
    ],
];
