<?php

return [
    'request_headers_tiktok' => [
        "x-secsdk-csrf-version: 1.2.5",
        "x-secsdk-csrf-request: 1"
    ],
    'signature_service' => env('ENDPOINT_TIKTOK_SIGNATURE', 'http://localhost:8080/signature'),
    'cookie_domain' => '.tiktok.com',
    'tiktok_cookie' => [
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1697897392.904224,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "tt-target-idc-sign",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "pbgqYWIySpD1H7tlAusirk4rDzoT5ZyXNYS_qd4vDCRmPMBTDBq0_9irTRkuLjJObDdyCkVlbpvyVUqSdcNsX3uYdm2snUCvlX_REha6XKvTpowKwYVHjt_Cz0L_feRjSyleUWBjxpjD3QTYpYbrH9cyzZA6OLQjb2HnPdESTqcGq5y3kF_dkwBlW8O2iBtY2fMvMBRTpAoGkNayHmnQ7G1ARkGM0CWw6X22TGa34C_iith_O535dlOKP0HUmvwKTF-WmgfE8MrM4cAAhLQCdxhp84LvJTZPVQjXv6q1UM0u_ji7I8ixlLS4ZbEKDu8qdh7fuSWvgyiqneU4aObWZseICl34bfjZ1T_o5FsLRa8it1QeFufba_lJZgnMl3JvUC7DGw9UDUyV6nhiDbO-juNblFiOQl9uX44vI-V9dsbuzTVDkfT49X8UZIoYxsABSg7yDDLN_tn556pOtrL7p0vVldZN38taZkpVSvGAHWOJDt4cNsQFUOKZvepwS5sX",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1697897374.634147,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "_abck",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "824AE04CC05786C851D56AA0DB1A4F35~-1~YAAQPlnKF3P9ae6DAQAAjLfg+ghhXODifw/WV8cI7SAShIYjC/eNfeTb+y/Ue6u1UperT34I7jO8tD2H/aFt62X3ze4vxphO+RODZLb+hOdUMu/GPgOLmRI05pBkstU8pBdhvUSQEgMGz0DKaaloR9lQRImo73BYA1GAaYDJfcB2NBiJ/xhCd5/7K27O9YY/fPScnvcl4WO+ckD4o3rNAMrq8aeXSErP62zXsMBFEPIBYfA0W2Uu9V5IVwnzaEQ1xe5Dq2JsdANIT+1i14XLVmPVna64qEcCGYDu8vDakwcjBgrLGU1ZHK70mUa19zNPi1vHaCUJ8r1S1zCiPPbyGYDUu3/y6eO3rqiynFCJCvE7/a0nGf91qruJvg==~-1~-1~-1",
        ],
        [
            "domain"   => "www.tiktok.com",
            "hostOnly" => true,
            "httpOnly" => false,
            "name"     => "csrf_session_id",
            "path"     => "/",
            "sameSite" => "no_restriction",
            "secure"   => true,
            "session"  => true,
            "storeId"  => null,
            "value"    => "0241a0a893d464398054f83bbc743ec7",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1667225521.142952,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "msToken",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "avWERrBwIt_OJNQdJHomHq88H3PiYC7jtU_9rljY1SE8tXEaPWkgJhVuMVLv_sf8p1epDLf0bETiHE-n5jxkhuuilFldRe_i44Zjn5cjpB4tzr5vUaVTGQkpSGVIj7ivDW46iRjKA5-htHHB",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1697465392.390448,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sid_guard",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "b8f8963f7232c97c91f2d5d3f9b02e64%7C1666361391%7C5184000%7CTue%2C+20-Dec-2022+14%3A09%3A51+GMT",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1697897400.079028,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "ttwid",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "1%7CnkbwtYFDdhIDv0F_tLNvJejyW7V6Wubl22iow5m7Hhs%7C1666361400%7C08e071b63d3294c034e3b34a791bd27c6a94678a1e66fe756e9e65ebb2babcdc",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.5381,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "store-country-code-src",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "uid",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.390485,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "uid_tt",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "a937c5f2c186d63f723a9c511a8053dcca97ad2a0c155595fc0884a924e5b2df",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545383.703232,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "passport_csrf_token_default",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "a3805e47e632429c01932ea3d113a566",
        ],
        [
            "domain"         => "www.tiktok.com",
            "expirationDate" => 1674137521,
            "hostOnly"       => true,
            "httpOnly"       => false,
            "name"           => "msToken",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "avWERrBwIt_OJNQdJHomHq88H3PiYC7jtU_9rljY1SE8tXEaPWkgJhVuMVLv_sf8p1epDLf0bETiHE-n5jxkhuuilFldRe_i44Zjn5cjpB4tzr5vUaVTGQkpSGVIj7ivDW46iRjKA5-htHHB",
        ],
        [
            "domain"   => ".tiktok.com",
            "hostOnly" => false,
            "httpOnly" => false,
            "name"     => "s_v_web_id",
            "path"     => "/",
            "sameSite" => "no_restriction",
            "secure"   => true,
            "session"  => true,
            "storeId"  => null,
            "value"    => "verify_l9ikjktn_t9PgCfBQ_ymdN_4Mpe_8C9N_cyOcJTf650Vv",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.537981,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "store-idc",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "useast2a",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.390701,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "ssid_ucp_v1",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "1.0.0-KDY0ZGVlZWQzNmVhYzBlODU2MDljZDE2YjZiNjliNGU1ZmU5YzZmYzYKIAiCiJHg5s7s5mEQr9DKmgYYswsgDDDM67iOBjgHQPQHEAMaBm1hbGl2YSIgYjhmODk2M2Y3MjMyYzk3YzkxZjJkNWQzZjliMDJlNjQ",
        ],
        [
            "domain"         => ".www.tiktok.com",
            "expirationDate" => 1666966197,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "__tea_cache_tokens_1988",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "{%22_type_%22:%22default%22%2C%22user_unique_id%22:%227156967560218134018%22%2C%22timestamp%22:1666361376988}",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1666375773.634184,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "bm_sz",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "90407EBE07373934B9ED5D710F314E46~YAAQPlnKF3T9ae6DAQAAjLfg+hEdtziteRDxBnk9R8vl7gz0sMaJlnLoaYXtqU7X4ln/bI7nVwheENAVU7JpiY+01j5hivNiNE+ou+PItsv+SJzjjkdN0JVUygPxySwdi9il9I5ERIq2Gp0iV6QJFq+OBtVnd4RTSbHnfu6JI2W9z9p54AOeFLewXYbKKBwh30Yr5YO20NY5i4m63JBmiFthxc1xXlCgf+4ANphfdlMsy7V7pWLXyTb9iSlllY1Mh0D2euH5a/IxP4YUPBaMKTW7ueLbEIOfUoICoM9OpHF3ZI0=~3425348~4276787",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.390385,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "cmpl_token",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "AgQQAPOFF-RO0rHzXNHkNp07-TMxIAhU_4AOYMRf5Q",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1697897523,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "mp_7ccb86f5c2939026a4b5de83b5971ed9_mixpanel",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "%7B%22distinct_id%22%3A%20%22183fae0b93e4b0-0e0955c9be21a4-11462c6d-1fa400-183fae0b93f5f8%22%2C%22%24device_id%22%3A%20%22183fae0b93e4b0-0e0955c9be21a4-11462c6d-1fa400-183fae0b93f5f8%22%2C%22site_type%22%3A%20%22similarweb%20extension%22%2C%22%24initial_referrer%22%3A%20%22https%3A%2F%2Fwww.tiktok.com%2Ffollowing%3Flang%3Dvi-VN%22%2C%22%24initial_referring_domain%22%3A%20%22www.tiktok.com%22%7D",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1697897401.052622,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "odin_tt",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "f31a5590187f392292965c85d8cc0444769810dd746c3b79db61b4a6496e5b6fe4bea43e978c627b53f376cc6221d2ce2a356ad46a42db912937401f94881efc06072cbc0b8f21bf5322b279d3fc4f28",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545383.703182,
            "hostOnly"       => false,
            "httpOnly"       => false,
            "name"           => "passport_csrf_token",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "a3805e47e632429c01932ea3d113a566",
        ],
        [
            "domain"   => ".www.tiktok.com",
            "hostOnly" => false,
            "httpOnly" => false,
            "name"     => "passport_fe_beating_status",
            "path"     => "/",
            "sameSite" => null,
            "secure"   => false,
            "session"  => true,
            "storeId"  => null,
            "value"    => "true",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.390567,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sessionid",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "b8f8963f7232c97c91f2d5d3f9b02e64",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.390602,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sessionid_ss",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          => "b8f8963f7232c97c91f2d5d3f9b02e64",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.390541,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sid_tt",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "b8f8963f7232c97c91f2d5d3f9b02e64",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.390658,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "sid_ucp_v1",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "1.0.0-KDY0ZGVlZWQzNmVhYzBlODU2MDljZDE2YjZiNjliNGU1ZmU5YzZmYzYKIAiCiJHg5s7s5mEQr9DKmgYYswsgDDDM67iOBjgHQPQHEAMaBm1hbGl2YSIgYjhmODk2M2Y3MjMyYzk3YzkxZjJkNWQzZjliMDJlNjQ",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.538064,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "store-country-code",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "vn",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.538128,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "tt-target-idc",
            "path"           => "/",
            "sameSite"       => null,
            "secure"         => false,
            "session"        => false,
            "storeId"        => null,
            "value"          => "alisg",
        ],
        [
            "domain"   => ".tiktok.com",
            "hostOnly" => false,
            "httpOnly" => true,
            "name"     => "tt_csrf_token",
            "path"     => "/",
            "sameSite" => "lax",
            "secure"   => true,
            "session"  => true,
            "storeId"  => null,
            "value"    => "ijrDNRqM-jz_sLsYWgB7U7dfmGhgrI-GybDk",
        ],
        [
            "domain"         => ".tiktok.com",
            "expirationDate" => 1671545392.390513,
            "hostOnly"       => false,
            "httpOnly"       => true,
            "name"           => "uid_tt_ss",
            "path"           => "/",
            "sameSite"       => "no_restriction",
            "secure"         => true,
            "session"        => false,
            "storeId"        => null,
            "value"          =>
                "a937c5f2c186d63f723a9c511a8053dcca97ad2a0c155595fc0884a924e5b2df",
        ],
    ],
];
